# Generated by Django 4.0 on 2024-03-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_listing_image_listing_image1_listing_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image1',
            new_name='image',
        ),
    ]
