# Generated by Django 4.0 on 2024-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_listing_image2_remove_listing_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_self',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='occupancy',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='occupation',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
