# Generated by Django 4.0 on 2024-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_listing_gender_remove_listing_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_self',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='occupancy',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='occupation',
        ),
        migrations.AddField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
    ]
