# Generated by Django 4.0 on 2024-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_image1_listing_image_remove_listing_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='RiteMate_project\\media\\properties_images'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent',
            field=models.IntegerField(),
        ),
    ]
