# Generated by Django 4.0 on 2024-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(null=True, upload_to='properties_images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(null=True, upload_to='properties_images'),
        ),
    ]
