# Generated by Django 4.0 on 2024-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_listing_image2_listing_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='about_partner',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='about_you',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='other_details',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='Any', max_length=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
